In [1]:
!pip install ramantune

Requirement already satisfied: ramantune in .\. (0.0.1)
Requirement already satisfied: ramanspy in .\.venv\Lib\site-packages (from ramantune) (0.2.10)
Requirement already satisfied: imbalanced-learn in .\.venv\Lib\site-packages (from ramantune) (0.14.2)
Requirement already satisfied: IS-Score in .\.venv\Lib\site-packages (from ramantune) (1.0.1)
Requirement already satisfied: pandas in .\.venv\Lib\site-packages (from ramantune) (3.0.5)
Requirement already satisfied: scikit-learn in .\.venv\Lib\site-packages (from ramantune) (1.9.0)
Requirement already satisfied: numpy<3,>=1.25.2 in .\.venv\Lib\site-packages (from imbalanced-learn->ramantune) (2.3.5)
Requirement already satisfied: scipy<2,>=1.11.4 in .\.venv\Lib\site-packages (from imbalanced-learn->ramantune) (1.18.0)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.6 in .\.venv\Lib\site-packages (from imbalanced-learn->ramantune) (0.1.6)
Requirement already satisfied: joblib<2,>=1.2.0 in .\.venv\Lib\site-packages (from imbalanced-learn->ramantune) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in .\.venv\Lib\site-packages (from imbalanced-learn->ramantune) (3.6.0)
Requirement already satisfied: narwhals>=2.0.1 in .\.venv\Lib\site-packages (from scikit-learn->ramantune) (2.24.0)
Requirement already satisfied: matplotlib in .\.venv\Lib\site-packages (from IS-Score->ramantune) (3.11.1)
Requirement already satisfied: seaborn in .\.venv\Lib\site-packages (from IS-Score->ramantune) (0.13.2)
Requirement already satisfied: PyQt5 in .\.venv\Lib\site-packages (from IS-Score->ramantune) (5.15.11)
Requirement already satisfied: qtmodern in .\.venv\Lib\site-packages (from IS-Score->ramantune) (0.2.0)
Requirement already satisfied: findpeaks in .\.venv\Lib\site-packages (from IS-Score->ramantune) (2.7.5)
Requirement already satisfied: orplib in .\.venv\Lib\site-packages (from IS-Score->ramantune) (1.0.10)
Requirement already satisfied: tqdm in .\.venv\Lib\site-packages (from findpeaks->IS-Score->ramantune) (4.70.0)
Requirement already satisfied: requests in .\.venv\Lib\site-packages (from findpeaks->IS-Score->ramantune) (2.34.2)
Requirement already satisfied: caerus>=1.0.1 in .\.venv\Lib\site-packages (from findpeaks->IS-Score->ramantune) (1.0.1)
Requirement already satisfied: xarray in .\.venv\Lib\site-packages (from findpeaks->IS-Score->ramantune) (2026.7.0)
Requirement already satisfied: adjustText in .\.venv\Lib\site-packages (from findpeaks->IS-Score->ramantune) (1.4.0)
Requirement already satisfied: opencv-python-headless in .\.venv\Lib\site-packages (from findpeaks->IS-Score->ramantune) (5.0.0.93)
Requirement already satisfied: datazets in .\.venv\Lib\site-packages (from caerus>=1.0.1->findpeaks->IS-Score->ramantune) (1.1.4)
Requirement already satisfied: contourpy>=1.0.1 in .\.venv\Lib\site-packages (from matplotlib->IS-Score->ramantune) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\.venv\Lib\site-packages (from matplotlib->IS-Score->ramantune) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in .\.venv\Lib\site-packages (from matplotlib->IS-Score->ramantune) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\.venv\Lib\site-packages (from matplotlib->IS-Score->ramantune) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\.venv\Lib\site-packages (from matplotlib->IS-Score->ramantune) (26.3)
Requirement already satisfied: pillow>=9 in .\.venv\Lib\site-packages (from matplotlib->IS-Score->ramantune) (12.3.0)
Requirement already satisfied: pyparsing>=3 in .\.venv\Lib\site-packages (from matplotlib->IS-Score->ramantune) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in .\.venv\Lib\site-packages (from matplotlib->IS-Score->ramantune) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib->IS-Score->ramantune) (1.17.0)
Requirement already satisfied: numba>=0.55.1 in .\.venv\Lib\site-packages (from orplib->IS-Score->ramantune) (0.67.0)
Requirement already satisfied: pyperclip>=1.8.2 in .\.venv\Lib\site-packages (from orplib->IS-Score->ramantune) (1.11.0)
Requirement already satisfied: ruamel.yaml>=0.17 in .\.venv\Lib\site-packages (from orplib->IS-Score->ramantune) (0.19.1)
Requirement already satisfied: sif-parser>=0.3.0 in .\.venv\Lib\site-packages (from orplib->IS-Score->ramantune) (0.3.6)
Requirement already satisfied: renishawWiRE>=0.1.16 in .\.venv\Lib\site-packages (from orplib->IS-Score->ramantune) (0.1.16)
Requirement already satisfied: llvmlite<0.50,>=0.49.0dev0 in .\.venv\Lib\site-packages (from numba>=0.55.1->orplib->IS-Score->ramantune) (0.49.0)
Requirement already satisfied: PyQt5-sip<13,>=12.15 in .\.venv\Lib\site-packages (from PyQt5->IS-Score->ramantune) (12.19.0)
Requirement already satisfied: PyQt5-Qt5<5.16.0,>=5.15.2 in .\.venv\Lib\site-packages (from PyQt5->IS-Score->ramantune) (5.15.2)
Requirement already satisfied: qtpy>=1.3.1 in .\.venv\Lib\site-packages (from qtmodern->IS-Score->ramantune) (2.4.3)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas->ramantune) (2026.3)
Requirement already satisfied: pybaselines in .\.venv\Lib\site-packages (from ramanspy->ramantune) (1.2.1)
Requirement already satisfied: pysptools in .\.venv\Lib\site-packages (from ramanspy->ramantune) (0.15.0)
Requirement already satisfied: cvxopt in .\.venv\Lib\site-packages (from ramanspy->ramantune) (1.3.3)
Requirement already satisfied: wget in .\.venv\Lib\site-packages (from ramanspy->ramantune) (3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in .\.venv\Lib\site-packages (from requests->findpeaks->IS-Score->ramantune) (3.5.0)
Requirement already satisfied: idna<4,>=2.5 in .\.venv\Lib\site-packages (from requests->findpeaks->IS-Score->ramantune) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in .\.venv\Lib\site-packages (from requests->findpeaks->IS-Score->ramantune) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\.venv\Lib\site-packages (from requests->findpeaks->IS-Score->ramantune) (2026.7.22)
Requirement already satisfied: colorama in .\.venv\Lib\site-packages (from tqdm->findpeaks->IS-Score->ramantune) (0.4.6)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd
from ramantune.pipeline.raman_pipeline import RamanPipeline

from ramantune.search.search_space import DenoiserSpace, BaselineSpace, NormalizerSpace, ClassifierSpace, FeatureSelectionSpace
from ramantune.utils.config import DENOISING_STR, BASELINE_STR, NORMALIZE_STR, FEATURE_SELECTION_STR, CLASSIFIER_STR
from ramantune.search.strategies import GridSearchStrategy
from ramantune.search import RamanSearch

from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("bin/ovarian_small.csv")
groups = df['patient']

y = df['label'].values
X = df.drop(columns=['label', 'patient'])

In [15]:
df

,401.226563,402.488281,403.75,405.010742,406.271484,407.53125,408.791992,410.051758,411.311523,412.570313,...,1995.704102,1996.632813,1997.561523,1998.489258,1999.416992,2000.344727,2001.272461,2002.199219,patient,label
0,45522.917969,45744.746094,46069.648438,45632.875000,45732.406250,45830.031250,45929.640625,45731.687500,45521.972656,45642.976563,...,14715.435547,14464.926758,14700.097656,14607.922852,14354.601563,14507.996094,14600.679688,14381.378906,1,HC
1,29890.923828,30093.746094,30147.046875,30052.671875,30222.613281,29856.013672,30201.003906,29952.884766,30206.605469,29841.615234,...,9622.037109,9497.227539,9615.257813,9485.115234,9450.002930,9483.558594,9506.558594,9474.852539,1,HC
2,15597.038086,15347.965820,15481.545898,15574.374023,15424.262695,15635.716797,15518.610352,15488.981445,15511.868164,15672.928711,...,4671.147949,4738.055664,4628.102051,4584.120605,4619.355957,4617.621582,4597.390625,4703.078125,1,HC
3,15505.758789,15616.035156,15776.876953,15702.637695,15579.769531,15760.148438,15436.933594,15751.572266,15825.101563,15900.608398,...,4752.958984,4587.599121,4686.184082,4639.573730,4518.992188,4585.921387,4689.867188,4607.959473,1,HC
4,14361.859375,14415.548828,14651.900391,14433.600586,14605.912109,14379.726563,14361.520508,14586.446289,14406.795898,14534.530273,...,4259.453613,4043.844482,4205.685547,4203.871094,4281.289551,4142.122559,4148.220703,4243.338867,1,HC
5,11835.181641,11863.058594,11655.847656,12066.543945,11767.925781,12044.672852,11761.472656,11806.871094,11733.610352,11790.697266,...,3425.508545,3515.927490,3403.093750,3422.246582,3351.608154,3471.141113,3411.052734,3474.464844,1,HC
6,16016.532227,16288.152344,16091.637695,16161.279297,16215.400391,16238.436523,16096.182617,16224.236328,16089.696289,16038.773438,...,5159.375488,5302.926758,5127.081543,5167.698242,5118.531250,5119.536621,5228.871582,5136.395508,1,HC
7,20543.576172,20724.900391,20789.726563,20805.996094,20892.246094,20677.175781,20971.515625,20721.351563,20570.296875,20829.777344,...,6368.067871,6403.633789,6093.359375,6303.165527,6201.399414,6176.200684,6121.927734,6140.423340,2,HC
8,22912.943359,22677.148438,22699.662109,22735.787109,22909.939453,23123.050781,22836.470703,22736.494141,22794.060547,23028.736328,...,6732.259277,6804.850586,6742.825195,6796.961914,6742.833008,6662.266113,6724.344727,6822.105469,2,HC
9,28399.386719,28289.130859,28310.945313,28530.994141,28416.798828,28380.322266,28326.326172,28243.125000,27710.464844,28286.775391,...,8906.850586,8892.762695,8857.547852,8877.772461,8736.894531,8714.835938,8745.611328,8785.244141,2,HC
10,27410.857422,27539.312500,27269.515625,27397.994141,27320.480469,27287.650391,27260.636719,27579.839844,27224.078125,27358.542969,...,8685.168945,8597.128906,8458.892578,8589.944336,8533.527344,8603.885742,8592.365234,8407.412109,2,HC
11,18574.283203,18448.250000,18473.712891,18332.052734,18579.093750,18266.296875,18705.953125,18400.824219,18527.470703,18436.220703,...,5774.277832,5624.956055,5742.225586,5669.416504,5517.343750,5645.227051,5643.693848,5635.767090,2,HC
12,22299.238281,22199.285156,22110.943359,22302.410156,22367.611328,22314.240234,22214.171875,22240.488281,22301.835938,22347.642578,...,6872.129883,6799.571289,6737.544922,6923.711914,6800.938477,6601.507813,6798.325684,6623.941895,2,HC
13,22804.185547,22519.802734,22752.121094,22450.107422,22587.263672,22671.982422,22556.435547,22473.902344,22634.525391,22824.408203,...,6887.964355,6957.946777,7022.676270,6892.024414,6977.894531,6807.557617,6816.820801,6798.325684,2,HC
14,33827.570313,33710.746094,33413.171875,33714.031250,33921.714844,33956.453125,34057.320313,34018.183594,33716.378906,33898.984375,...,12968.374023,12604.019531,12458.649414,12674.987305,12463.544922,12722.233398,12415.597656,12534.495117,3,HC
15,34480.117188,34540.207031,34534.261719,34804.273438,34611.773438,34596.113281,34599.890625,34928.500000,34426.503906,34373.804688,...,12672.798828,12807.267578,12783.382813,12561.440430,12619.372070,12616.567383,12825.134766,12809.282227,3,HC
16,32471.980469,32669.546875,32505.806641,32443.048828,32434.687500,32395.212891,32528.796875,32810.265625,32704.691406,32711.935547,...,12298.050781,12318.944336,12218.400391,12043.878906,12075.296875,12315.417969,12177.801758,12169.875000,3,HC
17,34802.503906,34800.507813,34835.421875,35014.160156,34837.257813,35008.296875,34854.644531,35115.230469,34786.429688,34922.570313,...,13200.611328,12928.688477,13052.672852,13155.581055,12999.696289,12835.825195,12835.704102,12917.611328,3,HC
18,32341.859375,32242.189453,32080.296875,32155.425781,32238.361328,32305.777344,32219.589844,32415.406250,32321.417969,32122.302734,...,11593.419922,11746.154297,11389.407227,11634.582031,11713.460938,11517.636719,11498.761719,11482.908203,3,HC
19,36074.582031,35740.695313,35735.015625,36071.367188,35748.914063,35651.843750,36132.304688,36027.492188,36095.785156,35924.750000,...,13704.673828,13699.447266,13549.012695,13485.658203,13564.900391,13707.573242,13493.606445,13543.807617,3,HC
20,36084.292969,35795.085938,35837.992188,36217.125000,36013.273438,35811.273438,36161.472656,36002.203125,36198.898438,35862.480469,...,13675.643555,13897.416016,13686.297852,13551.673828,13438.125977,13403.782227,13242.599609,13520.028320,3,HC
21,42518.484375,42226.816406,42391.613281,42651.707031,42270.449219,41999.843750,42495.320313,42298.554688,42197.027344,42410.703125,...,15082.266602,14995.483398,15183.236328,15120.204102,14814.160156,14991.419922,15049.849609,15041.922852,29,OC
22,25527.015625,25829.882813,25825.892578,25689.748047,25604.082031,25876.119141,25625.154297,25823.398438,25941.960938,25706.406250,...,9688.013672,9573.775391,9699.741211,9643.552734,9539.801758,9554.883789,9530.338867,9643.952148,29,OC
23,35053.035156,34742.230469,35014.175781,34786.785156,34780.886719,35056.902344,34790.468750,34753.437500,34860.359375,35237.820313,...,12886.562500,12989.398438,12881.066406,12915.284180,13192.500000,12962.625000,12967.812500,12938.749023,29,OC
24,22949.843750,22954.931641,23068.824219,23009.806641,22861.343750,22775.029297,22875.365234,22995.195313,22803.789063,22816.623047,...,8880.459961,8776.621094,8780.985352,8809.116211,8974.597656,8889.185547,8883.004883,8748.253906,29,OC
25,30716.318359,30744.494141,30648.332031,30901.935547,31070.123047,30655.103516,30815.525391,30997.414063,30739.685547,30974.175781,...,11353.264648,11342.297852,11452.770508,11404.847656,11327.854492,11145.163086,11118.288086,11279.460938,29,OC
26,30799.828125,30927.093750,31031.095703,31360.578125,31075.953125,31094.505859,31266.693359,30886.542969,30926.458984,31271.910156,...,12036.783203,11756.712891,12023.032227,11927.691406,11795.335938,11863.694336,11765.621094,11762.979492,29,OC
27,19729.835938,19811.910156,19822.130859,19665.222656,19708.457031,19860.587891,19660.794922,19739.066406,19733.710938,19909.328125,...,8613.914063,8515.301758,8411.371094,8648.038086,8491.268555,8675.210938,8579.154297,8550.089844,29,OC
28,11883.734375,11911.622070,12077.471680,12012.128906,11973.970703,12066.060547,11938.439453,12106.419922,11945.675781,12205.191406,...,3850.398438,3843.236084,3801.749512,3773.449463,3771.549561,3864.748291,3672.628418,3810.021729,30,OC
29,10390.256836,10602.353516,10369.604492,10478.790039,10278.954102,10477.601563,10448.808594,10488.081055,10441.765625,10311.751953,...,3296.194336,3357.552490,3255.248047,3192.512451,3135.034424,3304.716553,3212.889160,3223.458008,30,OC
30,12676.113281,12772.165039,12572.927734,12597.091797,12675.692383,12719.331055,12650.195313,12779.430664,12646.073242,12633.306641,...,4093.192383,4064.961182,4010.317627,4116.730469,4067.357178,3946.639893,3899.855713,3973.836670,30,OC
31,11353.540039,11361.884766,11323.600586,11466.035156,11206.159180,11317.521484,11413.374023,11188.323242,11157.727539,11241.930664,...,3494.124268,3589.835938,3500.777588,3649.340088,3518.000000,3666.623779,3606.573975,3506.171143,30,OC
32,12522.686523,12476.899414,12454.406250,12350.280273,12592.107422,12365.475586,12362.381836,12409.858398,12507.939453,12292.759766,...,4101.109863,4028.007080,3957.515625,3939.808594,3887.759766,3885.881592,3891.929199,3905.140137,30,OC
33,12375.086914,12556.543945,12347.543945,12589.317383,12366.624023,12620.173828,12687.144531,12581.028320,12467.083008,12444.546875,...,3963.878174,3880.190186,3873.032227,3900.199219,3882.477295,3920.223145,3862.865234,3976.478760,30,OC
34,12134.266602,12261.278320,12378.630859,12247.280273,12255.826172,12112.722656,12175.691406,12114.200195,12126.611328,12131.244141,...,4003.464111,4014.809082,4034.078613,3963.574219,3821.731201,3994.189697,3836.443359,3862.865234,30,OC
35,16101.984375,15992.886719,16252.903320,16285.656250,16374.793945,16481.468750,16245.923828,16374.010742,16221.994141,16390.996094,...,6935.467285,6907.794434,7030.596191,6802.243164,6779.809082,6749.440918,6964.782715,6983.278320,31,OC
36,23625.695313,23778.566406,23799.380859,23866.843750,23648.591797,23914.363281,23814.648438,23897.730469,23617.029297,23795.453125,...,10437.508789,10318.138672,10217.201172,10258.818359,10255.550781,10365.873047,10301.854492,10029.709961,31,OC
37,36105.656250,36078.695313,36436.425781,36533.898438,36732.488281,36544.257813,36375.390625,36455.417969,36366.214844,36345.082031,...,12949.900391,13034.271484,12894.266602,13102.768555,13131.753906,12727.517578,12859.483398,12817.208984,31,OC
38,30650.287109,31010.621094,30805.712891,30952.464844,31262.560547,30812.587891,30957.488281,31184.144531,30871.984375,31015.041016,...,13828.709961,13815.588867,13683.658203,13625.611328,13556.977539,13496.240234,13567.587891,13554.376953,31,OC
39,21759.333984,21608.753906,21774.810547,21723.277344,21856.384766,21767.904297,21879.685547,21894.257813,21449.685547,21664.603516,...,6845.739258,7013.377930,6832.588379,6947.477539,7028.076660,7000.398438,6848.526855,6737.555664,31,OC
40,14268.638672,14347.560547,14333.253906,14212.053711,14187.989258,14362.227539,14485.980469,14226.599609,14344.538086,14310.742188,...,6135.830078,6253.177246,6138.241211,6226.587402,6037.648438,6075.817871,6148.349609,6140.423340,31,OC
41,13614.149414,13648.248047,13713.448242,13636.808594,13760.347656,13703.125000,13708.105469,13835.629883,13675.269531,13684.136719,...,5932.622070,6015.614746,5784.467285,5841.056641,6024.442871,5851.276367,5907.911621,5915.837891,31,OC

In [16]:
df['label'].value_counts()

label
HC    21
OC    21
Name: count, dtype: int64

In [17]:
df['patient'].value_counts()

patient
1     7
2     7
3     7
29    7
30    7
31    7
Name: count, dtype: int64

In [6]:
from ramantune.utils import register_algorithm
from ramantune.custom import RamanPipelineStep
from orpl.baseline_removal import bubblefill

@register_algorithm(category=NORMALIZE_STR, name="snv")
class SNVNormalization(RamanPipelineStep):
    def __init__(self):
        super().__init__(self.snv_normalization)

    @staticmethod
    def snv_normalization(spectral_data, spectral_axis):
        mean, std = spectral_data.mean(), spectral_data.std()
        return (spectral_data - mean) / std, spectral_axis

@register_algorithm(category=BASELINE_STR, name="bubblefill")
class BubbleFill(RamanPipelineStep):
    def __init__(self, *, min_bubble_widths=50, fit_order=1):
        super().__init__(
            self._bubblefill_call,
            min_bubble_widths=min_bubble_widths,
            fit_order=fit_order
        )

    @staticmethod
    def _bubblefill_call(spectral_data, spectral_axis, *args, **kwargs):
        raman, bubblefill_b = bubblefill(
            spectral_data,
            min_bubble_widths=kwargs.get("min_bubble_widths", 50),
            fit_order=kwargs.get("fit_order", 1))
        return raman, spectral_axis

In [9]:
def setup_param_grid():
  denoiser_list = [
        DenoiserSpace("savgol", {"window_length": [7], "polyorder": [3]}),
  ]

  baseline_list = [
      BaselineSpace("asls", {"lam": [100]}),
      BaselineSpace("bubblefill", {"min_bubble_widths": [50]}),
  ]

  normalization_list = [
      NormalizerSpace("snv"),
      NormalizerSpace("vector"),
  ]

  feature_selection_list = [
      FeatureSelectionSpace(None), # No feature selection
      FeatureSelectionSpace(PCA(),{"n_components": [0.90, 10]}),
  ]

  classifier_list = [
      ClassifierSpace(SVC(),{"C": [0.1, 10], "kernel": ["rbf"], "gamma": ["scale"]}),
      ClassifierSpace(RandomForestClassifier(),{"n_estimators": [100, 200]})
  ]

  param_list = {
      DENOISING_STR: denoiser_list,
      BASELINE_STR: baseline_list,
      NORMALIZE_STR: normalization_list,
      FEATURE_SELECTION_STR: feature_selection_list,
      CLASSIFIER_STR: classifier_list
  }

  return param_list

In [10]:
estimator = RamanPipeline()
param_grid = setup_param_grid()

In [11]:
search = RamanSearch(estimator=estimator,
                     research_strategy=GridSearchStrategy(),
                     param_grid=param_grid,
                     cv=StratifiedGroupKFold(n_splits=2, random_state=42, shuffle=True),
                     return_train_score=True,
                     n_jobs=1,
                     verbose=10,
                     refit="accuracy")

res = search.fit(X, y, groups=groups)

Fitting 2 folds for each of 48 candidates, totalling 96 fits
[CV 1/2; 1/48] START baseline__algorithm=asls, baseline__lam=100, classifier__C=0.1, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=None, normalize__algorithm=snv
[CV 1/2; 1/48] END baseline__algorithm=asls, baseline__lam=100, classifier__C=0.1, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=None, normalize__algorithm=snv; accuracy: (train=0.667, test=0.333) f1: (train=0.400, test=0.250) patient_accuracy: (train=0.667, test=0.333) precision: (train=0.333, test=0.167) recall: (train=0.500, test=0.500) sensitivity: (train=0.500, test=0.500) specificity: (train=0.500, test=0.500) total time=   0.2s
[CV 2/2; 1/48] START baseline__algorithm=asls, baseline__lam=100, classifier__C=0.1, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=None, normalize__algorithm=snv
[CV 2/2; 1/48] END baseline__algorithm=asls, baseline__lam=100, classifier__C=0.1, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=None, normalize__algorithm=snv; accuracy: (train=0.667, test=0.333) f1: (train=0.400, test=0.250) patient_accuracy: (train=0.667, test=0.333) precision: (train=0.333, test=0.167) recall: (train=0.500, test=0.500) sensitivity: (train=0.500, test=0.500) specificity: (train=0.500, test=0.500) total time=   0.1s
[CV 1/2; 2/48] START baseline__algorithm=asls, baseline__lam=100, classifier__C=10, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=None, normalize__algorithm=snv
[CV 1/2; 2/48] END baseline__algorithm=asls, baseline__lam=100, classifier__C=10, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=None, normalize__algorithm=snv; accuracy: (train=1.000, test=0.571) f1: (train=1.000, test=0.568) patient_accuracy: (train=1.000, test=0.667) precision: (train=1.000, test=0.597) recall: (train=1.000, test=0.607) sensitivity: (train=1.000, test=0.607) specificity: (train=1.000, test=0.607) total time=   0.1s
[CV 2/2; 2/48] START baseline__algorithm=asls, baseline__lam=100, classifier__C=10, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=None, normalize__algorithm=snv
[CV 2/2; 2/48] END baseline__algorithm=asls, baseline__lam=100, classifier__C=10, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=None, normalize__algorithm=snv; accuracy: (train=1.000, test=0.429) f1: (train=1.000, test=0.394) patient_accuracy: (train=1.000, test=0.333) precision: (train=1.000, test=0.684) recall: (train=1.000, test=0.571) sensitivity: (train=1.000, test=0.571) specificity: (train=1.000, test=0.571) total time=   0.1s
[CV 1/2; 3/48] START baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=100, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=None, normalize__algorithm=snv
[CV 1/2; 3/48] END baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=100, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=None, normalize__algorithm=snv; accuracy: (train=1.000, test=0.286) f1: (train=1.000, test=0.222) patient_accuracy: (train=1.000, test=0.333) precision: (train=1.000, test=0.150) recall: (train=1.000, test=0.429) sensitivity: (train=1.000, test=0.429) specificity: (train=1.000, test=0.429) total time=   0.2s
[CV 2/2; 3/48] START baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=100, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=None, normalize__algorithm=snv
[CV 2/2; 3/48] END baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=100, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=None, normalize__algorithm=snv; accuracy: (train=1.000, test=0.333) f1: (train=1.000, test=0.250) patient_accuracy: (train=1.000, test=0.333) precision: (train=1.000, test=0.167) recall: (train=1.000, test=0.500) sensitivity: (train=1.000, test=0.500) specificity: (train=1.000, test=0.500) total time=   0.2s
[CV 1/2; 4/48] START baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=200, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=None, normalize__algorithm=snv
[CV 1/2; 4/48] END baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=200, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=None, normalize__algorithm=snv; accuracy: (train=1.000, test=0.333) f1: (train=1.000, test=0.250) patient_accuracy: (train=1.000, test=0.333) precision: (train=1.000, test=0.167) recall: (train=1.000, test=0.500) sensitivity: (train=1.000, test=0.500) specificity: (train=1.000, test=0.500) total time=   0.4s
[CV 2/2; 4/48] START baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=200, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=None, normalize__algorithm=snv
[CV 2/2; 4/48] END baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=200, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=None, normalize__algorithm=snv; accuracy: (train=1.000, test=0.333) f1: (train=1.000, test=0.250) patient_accuracy: (train=1.000, test=0.333) precision: (train=1.000, test=0.167) recall: (train=1.000, test=0.500) sensitivity: (train=1.000, test=0.500) specificity: (train=1.000, test=0.500) total time=   0.4s
[CV 1/2; 5/48] START baseline__algorithm=asls, baseline__lam=100, classifier__C=0.1, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=0.9, normalize__algorithm=snv
[CV 1/2; 5/48] END baseline__algorithm=asls, baseline__lam=100, classifier__C=0.1, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=0.9, normalize__algorithm=snv; accuracy: (train=0.667, test=0.333) f1: (train=0.400, test=0.250) patient_accuracy: (train=0.667, test=0.333) precision: (train=0.333, test=0.167) recall: (train=0.500, test=0.500) sensitivity: (train=0.500, test=0.500) specificity: (train=0.500, test=0.500) total time=   0.0s
[CV 2/2; 5/48] START baseline__algorithm=asls, baseline__lam=100, classifier__C=0.1, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=0.9, normalize__algorithm=snv
[CV 2/2; 5/48] END baseline__algorithm=asls, baseline__lam=100, classifier__C=0.1, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=0.9, normalize__algorithm=snv; accuracy: (train=0.667, test=0.333) f1: (train=0.400, test=0.250) patient_accuracy: (train=0.667, test=0.333) precision: (train=0.333, test=0.167) recall: (train=0.500, test=0.500) sensitivity: (train=0.500, test=0.500) specificity: (train=0.500, test=0.500) total time=   0.0s
[CV 1/2; 6/48] START baseline__algorithm=asls, baseline__lam=100, classifier__C=0.1, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=10, normalize__algorithm=snv
[CV 1/2; 6/48] END baseline__algorithm=asls, baseline__lam=100, classifier__C=0.1, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=10, normalize__algorithm=snv; accuracy: (train=0.667, test=0.333) f1: (train=0.400, test=0.250) patient_accuracy: (train=0.667, test=0.333) precision: (train=0.333, test=0.167) recall: (train=0.500, test=0.500) sensitivity: (train=0.500, test=0.500) specificity: (train=0.500, test=0.500) total time=   0.1s
[CV 2/2; 6/48] START baseline__algorithm=asls, baseline__lam=100, classifier__C=0.1, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=10, normalize__algorithm=snv
[CV 2/2; 6/48] END baseline__algorithm=asls, baseline__lam=100, classifier__C=0.1, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=10, normalize__algorithm=snv; accuracy: (train=0.667, test=0.333) f1: (train=0.400, test=0.250) patient_accuracy: (train=0.667, test=0.333) precision: (train=0.333, test=0.167) recall: (train=0.500, test=0.500) sensitivity: (train=0.500, test=0.500) specificity: (train=0.500, test=0.500) total time=   0.1s
[CV 1/2; 7/48] START baseline__algorithm=asls, baseline__lam=100, classifier__C=10, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=0.9, normalize__algorithm=snv
[CV 1/2; 7/48] END baseline__algorithm=asls, baseline__lam=100, classifier__C=10, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=0.9, normalize__algorithm=snv; accuracy: (train=1.000, test=0.667) f1: (train=1.000, test=0.400) patient_accuracy: (train=1.000, test=0.667) precision: (train=1.000, test=0.333) recall: (train=1.000, test=0.500) sensitivity: (train=1.000, test=0.500) specificity: (train=1.000, test=0.500) total time=   0.1s
[CV 2/2; 7/48] START baseline__algorithm=asls, baseline__lam=100, classifier__C=10, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=0.9, normalize__algorithm=snv
[CV 2/2; 7/48] END baseline__algorithm=asls, baseline__lam=100, classifier__C=10, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=0.9, normalize__algorithm=snv; accuracy: (train=1.000, test=0.429) f1: (train=1.000, test=0.394) patient_accuracy: (train=1.000, test=0.333) precision: (train=1.000, test=0.684) recall: (train=1.000, test=0.571) sensitivity: (train=1.000, test=0.571) specificity: (train=1.000, test=0.571) total time=   0.1s
[CV 1/2; 8/48] START baseline__algorithm=asls, baseline__lam=100, classifier__C=10, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=10, normalize__algorithm=snv
[CV 1/2; 8/48] END baseline__algorithm=asls, baseline__lam=100, classifier__C=10, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=10, normalize__algorithm=snv; accuracy: (train=1.000, test=0.714) f1: (train=1.000, test=0.606) patient_accuracy: (train=1.000, test=0.667) precision: (train=1.000, test=0.694) recall: (train=1.000, test=0.607) sensitivity: (train=1.000, test=0.607) specificity: (train=1.000, test=0.607) total time=   0.1s
[CV 2/2; 8/48] START baseline__algorithm=asls, baseline__lam=100, classifier__C=10, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=10, normalize__algorithm=snv
[CV 2/2; 8/48] END baseline__algorithm=asls, baseline__lam=100, classifier__C=10, classifier__algorithm=SVC(), denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=10, normalize__algorithm=snv; accuracy: (train=1.000, test=0.524) f1: (train=1.000, test=0.523) patient_accuracy: (train=1.000, test=0.667) precision: (train=1.000, test=0.567) recall: (train=1.000, test=0.571) sensitivity: (train=1.000, test=0.571) specificity: (train=1.000, test=0.571) total time=   0.2s
[CV 1/2; 9/48] START baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=100, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=0.9, normalize__algorithm=snv
[CV 1/2; 9/48] END baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=100, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=0.9, normalize__algorithm=snv; accuracy: (train=1.000, test=0.619) f1: (train=1.000, test=0.618) patient_accuracy: (train=1.000, test=0.667) precision: (train=1.000, test=0.733) recall: (train=1.000, test=0.714) sensitivity: (train=1.000, test=0.714) specificity: (train=1.000, test=0.714) total time=   0.5s
[CV 2/2; 9/48] START baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=100, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=0.9, normalize__algorithm=snv
[CV 2/2; 9/48] END baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=100, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=0.9, normalize__algorithm=snv; accuracy: (train=1.000, test=0.333) f1: (train=1.000, test=0.250) patient_accuracy: (train=1.000, test=0.333) precision: (train=1.000, test=0.167) recall: (train=1.000, test=0.500) sensitivity: (train=1.000, test=0.500) specificity: (train=1.000, test=0.500) total time=   0.4s
[CV 1/2; 10/48] START baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=100, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=10, normalize__algorithm=snv
[CV 1/2; 10/48] END baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=100, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=10, normalize__algorithm=snv; accuracy: (train=1.000, test=0.619) f1: (train=1.000, test=0.618) patient_accuracy: (train=1.000, test=0.667) precision: (train=1.000, test=0.733) recall: (train=1.000, test=0.714) sensitivity: (train=1.000, test=0.714) specificity: (train=1.000, test=0.714) total time=   0.5s
[CV 2/2; 10/48] START baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=100, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=10, normalize__algorithm=snv
[CV 2/2; 10/48] END baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=100, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=10, normalize__algorithm=snv; accuracy: (train=1.000, test=0.333) f1: (train=1.000, test=0.250) patient_accuracy: (train=1.000, test=0.333) precision: (train=1.000, test=0.167) recall: (train=1.000, test=0.500) sensitivity: (train=1.000, test=0.500) specificity: (train=1.000, test=0.500) total time=   0.9s
[CV 1/2; 11/48] START baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=200, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=0.9, normalize__algorithm=snv
[CV 1/2; 11/48] END baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=200, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=0.9, normalize__algorithm=snv; accuracy: (train=1.000, test=0.619) f1: (train=1.000, test=0.618) patient_accuracy: (train=1.000, test=0.667) precision: (train=1.000, test=0.733) recall: (train=1.000, test=0.714) sensitivity: (train=1.000, test=0.714) specificity: (train=1.000, test=0.714) total time=   0.7s
[CV 2/2; 11/48] START baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=200, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=0.9, normalize__algorithm=snv
[CV 2/2; 11/48] END baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=200, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=0.9, normalize__algorithm=snv; accuracy: (train=1.000, test=0.333) f1: (train=1.000, test=0.250) patient_accuracy: (train=1.000, test=0.333) precision: (train=1.000, test=0.167) recall: (train=1.000, test=0.500) sensitivity: (train=1.000, test=0.500) specificity: (train=1.000, test=0.500) total time=   0.4s
[CV 1/2; 12/48] START baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=200, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=10, normalize__algorithm=snv
[CV 1/2; 12/48] END baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=200, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=10, normalize__algorithm=snv; accuracy: (train=1.000, test=0.619) f1: (train=1.000, test=0.618) patient_accuracy: (train=1.000, test=0.667) precision: (train=1.000, test=0.733) recall: (train=1.000, test=0.714) sensitivity: (train=1.000, test=0.714) specificity: (train=1.000, test=0.714) total time=   0.5s
[CV 2/2; 12/48] START baseline__algorithm=asls, baseline__lam=100, classifier__algorithm=RandomForestClassifier(), classifier__n_estimators=200, denoising__algorithm=savgol, denoising__polyorder=3, denoising__window_length=7, feature__algorithm=PCA(), feature__n_components=10, normalize__algorithm=snv

In [12]:
print(search.get_best_params())
print(search.get_best_score())

{'baseline__algorithm': 'asls', 'baseline__lam': 100, 'classifier__C': 10, 'classifier__algorithm': SVC(), 'denoising__algorithm': 'savgol', 'denoising__polyorder': 3, 'denoising__window_length': 7, 'feature__algorithm': PCA(), 'feature__n_components': 10, 'normalize__algorithm': 'snv'}
0.6190476190476191

In [13]:
result_cv = search.get_cv_results(file_path=f"result_add_preprocessing.csv",
                          return_split_scores=False,
                          return_combined_params=True,
                          round_values=True)

In [14]:
result_cv

,denoising,baseline,normalize,feature,classifier,mean_fit_time,std_fit_time,mean_score_time,std_score_time,split0_test_accuracy,...,std_train_sensitivity,split0_test_patient_accuracy,split1_test_patient_accuracy,mean_test_patient_accuracy,std_test_patient_accuracy,rank_test_patient_accuracy,split0_train_patient_accuracy,split1_train_patient_accuracy,mean_train_patient_accuracy,std_train_patient_accuracy
0,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),snv,None,SVC(C=0.1),0.0835,0.0233,0.1306,0.0364,0.3333,...,0.0,0.3333,0.3333,0.3333,0.0000,25,0.6667,0.6667,0.6667,0.0
1,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),snv,None,SVC(C=10.0),0.0729,0.0017,0.1075,0.0102,0.5714,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
2,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),snv,None,RandomForestClassifier(n_estimators=100.0),0.1627,0.0272,0.1426,0.0400,0.2857,...,0.0,0.3333,0.3333,0.3333,0.0000,25,1.0000,1.0000,1.0000,0.0
3,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),snv,None,RandomForestClassifier(n_estimators=200.0),0.3318,0.0180,0.1586,0.0211,0.3333,...,0.0,0.3333,0.3333,0.3333,0.0000,25,1.0000,1.0000,1.0000,0.0
4,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),snv,PCA(n_components=0.9),SVC(C=0.1),0.0585,0.0010,0.0840,0.0023,0.3333,...,0.0,0.3333,0.3333,0.3333,0.0000,25,0.6667,0.6667,0.6667,0.0
5,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),snv,PCA(n_components=10.0),SVC(C=0.1),0.1074,0.0291,0.0846,0.0029,0.3333,...,0.0,0.3333,0.3333,0.3333,0.0000,25,0.6667,0.6667,0.6667,0.0
6,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),snv,PCA(n_components=0.9),SVC(C=10.0),0.0804,0.0228,0.1189,0.0234,0.6667,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
7,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),snv,PCA(n_components=10.0),SVC(C=10.0),0.1077,0.0041,0.1492,0.0551,0.7143,...,0.0,0.6667,0.6667,0.6667,0.0000,1,1.0000,1.0000,1.0000,0.0
8,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),snv,PCA(n_components=0.9),RandomForestClassifier(n_estimators=100.0),0.3302,0.1026,0.2410,0.0774,0.6190,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
9,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),snv,PCA(n_components=10.0),RandomForestClassifier(n_estimators=100.0),0.4399,0.1187,0.3375,0.1031,0.6190,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
10,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),snv,PCA(n_components=0.9),RandomForestClassifier(n_estimators=200.0),0.3868,0.0708,0.2501,0.0507,0.6190,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
11,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),snv,PCA(n_components=10.0),RandomForestClassifier(n_estimators=200.0),0.4270,0.0306,0.1960,0.0241,0.6190,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
12,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),vector,None,SVC(C=0.1),0.0630,0.0114,0.1186,0.0353,0.3333,...,0.0,0.3333,0.3333,0.3333,0.0000,25,0.6667,0.6667,0.6667,0.0
13,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),vector,None,SVC(C=10.0),0.1894,0.0569,0.0865,0.0007,0.5714,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
14,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),vector,None,RandomForestClassifier(n_estimators=100.0),0.2734,0.0052,0.0992,0.0042,0.3333,...,0.0,0.3333,0.3333,0.3333,0.0000,25,1.0000,1.0000,1.0000,0.0
15,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),vector,None,RandomForestClassifier(n_estimators=200.0),0.3279,0.0474,0.1705,0.0069,0.3333,...,0.0,0.3333,0.3333,0.3333,0.0000,25,1.0000,1.0000,1.0000,0.0
16,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),vector,PCA(n_components=0.9),SVC(C=0.1),0.1394,0.0277,0.1543,0.0503,0.3333,...,0.0,0.3333,0.3333,0.3333,0.0000,25,0.6667,0.6667,0.6667,0.0
17,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),vector,PCA(n_components=10.0),SVC(C=0.1),0.1015,0.0460,0.1238,0.0251,0.3333,...,0.0,0.3333,0.3333,0.3333,0.0000,25,0.6667,0.6667,0.6667,0.0
18,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),vector,PCA(n_components=0.9),SVC(C=10.0),0.1851,0.0693,0.1612,0.0354,0.6190,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
19,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),vector,PCA(n_components=10.0),SVC(C=10.0),0.0815,0.0248,0.1038,0.0178,0.6190,...,0.0,0.3333,0.6667,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
20,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),vector,PCA(n_components=0.9),RandomForestClassifier(n_estimators=100.0),0.2507,0.0152,0.2222,0.0243,0.6190,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
21,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),vector,PCA(n_components=10.0),RandomForestClassifier(n_estimators=100.0),0.3246,0.0674,0.1881,0.0118,0.5714,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
22,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),vector,PCA(n_components=0.9),RandomForestClassifier(n_estimators=200.0),0.4759,0.0104,0.1539,0.0365,0.5714,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
23,"savgol(polyorder=3,window_length=7)",asls(lam=100.0),vector,PCA(n_components=10.0),RandomForestClassifier(n_estimators=200.0),0.6471,0.0737,0.2259,0.0521,0.5714,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
24,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),snv,None,SVC(C=0.1),0.3958,0.2182,0.2011,0.0114,0.3333,...,0.0,0.3333,0.3333,0.3333,0.0000,25,0.6667,0.6667,0.6667,0.0
25,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),snv,None,SVC(C=10.0),0.1449,0.0696,0.2948,0.1097,0.5714,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
26,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),snv,None,RandomForestClassifier(n_estimators=100.0),0.3193,0.0851,0.1813,0.0028,0.4286,...,0.0,0.3333,0.3333,0.3333,0.0000,25,1.0000,1.0000,1.0000,0.0
27,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),snv,None,RandomForestClassifier(n_estimators=200.0),0.4190,0.0592,0.2940,0.1443,0.4286,...,0.0,0.3333,0.3333,0.3333,0.0000,25,1.0000,1.0000,1.0000,0.0
28,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),snv,PCA(n_components=0.9),SVC(C=0.1),0.0744,0.0012,0.2084,0.0583,0.3333,...,0.0,0.3333,0.3333,0.3333,0.0000,25,0.6667,0.6667,0.6667,0.0
29,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),snv,PCA(n_components=10.0),SVC(C=0.1),0.0830,0.0004,0.1209,0.0027,0.3333,...,0.0,0.3333,0.3333,0.3333,0.0000,25,0.6667,0.6667,0.6667,0.0
30,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),snv,PCA(n_components=0.9),SVC(C=10.0),0.0961,0.0160,0.1456,0.0245,0.4286,...,0.0,0.3333,0.3333,0.3333,0.0000,25,1.0000,1.0000,1.0000,0.0
31,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),snv,PCA(n_components=10.0),SVC(C=10.0),0.0826,0.0086,0.2768,0.1006,0.5238,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
32,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),snv,PCA(n_components=0.9),RandomForestClassifier(n_estimators=100.0),0.2847,0.0382,0.2696,0.1356,0.4286,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
33,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),snv,PCA(n_components=10.0),RandomForestClassifier(n_estimators=100.0),0.1900,0.0098,0.1462,0.0088,0.5238,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
34,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),snv,PCA(n_components=0.9),RandomForestClassifier(n_estimators=200.0),0.2436,0.0038,0.1554,0.0131,0.5238,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
35,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),snv,PCA(n_components=10.0),RandomForestClassifier(n_estimators=200.0),0.3902,0.0357,0.1865,0.0156,0.5238,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
36,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),vector,None,SVC(C=0.1),0.0776,0.0080,0.1191,0.0021,0.3333,...,0.0,0.3333,0.3333,0.3333,0.0000,25,0.6667,0.6667,0.6667,0.0
37,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),vector,None,SVC(C=10.0),0.1142,0.0251,0.2302,0.0417,0.5714,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
38,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),vector,None,RandomForestClassifier(n_estimators=100.0),0.2588,0.0070,0.2892,0.0235,0.3333,...,0.0,0.3333,0.3333,0.3333,0.0000,25,1.0000,1.0000,1.0000,0.0
39,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),vector,None,RandomForestClassifier(n_estimators=200.0),0.5239,0.0146,0.2357,0.0142,0.3810,...,0.0,0.3333,0.3333,0.3333,0.0000,25,1.0000,1.0000,1.0000,0.0
40,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),vector,PCA(n_components=0.9),SVC(C=0.1),0.1414,0.0519,0.2866,0.0238,0.3333,...,0.0,0.3333,0.3333,0.3333,0.0000,25,0.6667,0.6667,0.6667,0.0
41,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),vector,PCA(n_components=10.0),SVC(C=0.1),0.1495,0.0464,0.2155,0.0108,0.3333,...,0.0,0.3333,0.3333,0.3333,0.0000,25,0.6667,0.6667,0.6667,0.0
42,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),vector,PCA(n_components=0.9),SVC(C=10.0),0.1812,0.0174,0.1519,0.0158,0.4286,...,0.0,0.3333,0.3333,0.3333,0.0000,25,1.0000,1.0000,1.0000,0.0
43,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),vector,PCA(n_components=10.0),SVC(C=10.0),0.1590,0.0043,0.2565,0.0750,0.5238,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
44,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),vector,PCA(n_components=0.9),RandomForestClassifier(n_estimators=100.0),0.2475,0.0786,0.1843,0.0354,0.4286,...,0.0,0.3333,0.3333,0.3333,0.0000,25,1.0000,1.0000,1.0000,0.0
45,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),vector,PCA(n_components=10.0),RandomForestClassifier(n_estimators=100.0),0.2290,0.0521,0.1941,0.0339,0.4762,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0
46,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),vector,PCA(n_components=0.9),RandomForestClassifier(n_estimators=200.0),0.4019,0.1016,0.2818,0.0281,0.3810,...,0.0,0.3333,0.3333,0.3333,0.0000,25,1.0000,1.0000,1.0000,0.0
47,"savgol(polyorder=3,window_length=7)",bubblefill(min_bubble_widths=50.0),vector,PCA(n_components=10.0),RandomForestClassifier(n_estimators=200.0),0.4607,0.0483,0.2772,0.0560,0.5238,...,0.0,0.6667,0.3333,0.5000,0.1667,2,1.0000,1.0000,1.0000,0.0